name = "aunit"
description = "aunit tests"
version = "0.1.0-dev"
project-files = ["aunit.gpr"]

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]

[[depends-on]]
ada_lib = "*"

[[pins]]
ada_lib = { path = "../ada_lib" }

[[depends-on]]
applications = "*"

[[pins]]
applications = { path = ".." }

[[depends-on]]
ada_lib_gnoga = "*"

[[pins]]
ada_lib_gnoga  = { path = "../gnoga = { path ="/Users/Wayne/GNAT/share/gpr" }/ada_lib_gnoga" }

[[depends-on]]
gnoga = "*"

[[pins]]
gnoga = { path ="/Users/Wayne/GNAT/share" }

