name = "aunit"
description = ""
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
maintainers-logins = ["github-username"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
alr_environment = "*"

[[pins]]
alr_environment = { path='..' }

[[depends-on]]
ada_lib = "~0.1.0-dev"

[[pins]]
ada_lib = { path='../ada_lib' }


[[depends-on]]
gnatcoll = "^25.0.0"


